asp/asp/Controllers/FileController.cs
using System;
using System.Configuration;
//-----------------------------------------------------------------------
// <copyright file="FileController.cs" company="ICT4Participation">
//     Copyright (c) ICT4Participation. All rights reserved.
// </copyright>
// <author>ICT4Participation</author>
//-----------------------------------------------------------------------
using System.IO;
using System.Web;
using System.Web.Mvc;
using asp.Data;
using asp.Models;
using Asp.Models;
using Asp.Models.Users;

namespace asp.Controllers
{
    /// <summary>
    /// This class is the file controller
    /// the file controller contains all methods which are needed to upload a file into the database
    /// (e.g. profile image)
    /// </summary>
    public class FileController : Controller
    {
        /// <summary>
        /// this action result will save a profile image into the database
        /// </summary>
        /// <returns> redirect dashboard, home controller </returns>
        [HttpPost]
        public ActionResult UploadProfileImage()
        {
            try
            {
                this.Import(this.Request, "IMPORT_FILE");
            }
            catch (Exception e)
            {
                //// show exception message through remodal
                ViewBag.ShowRemodal = "Show";
                this.TempData["RemodalMessage"] = new TechnicalErrorMessage(e).ErrorMessage;
            }

            return this.RedirectToAction("Dashboard", "Home");
        }

        /// <summary>
        /// this action result will save a VOG into the database
        /// </summary>
        /// <returns> redirect dashboard, home controller </returns>
        [HttpPost]
        public ActionResult UploadVog()
        {
            try
            {
                this.Import(this.Request, "IMPORT_VOG");
            }
            catch (Exception e)
            {
                //// show exception message through remodal
                ViewBag.ShowRemodal = "Show";
                this.TempData["RemodalMessage"] = new TechnicalErrorMessage(e).ErrorMessage;
            }

            return this.RedirectToAction("Dashboard", "Home");
        }

        /// <summary>
        /// this method will save a profile image into the database
        /// </summary>
        /// <param name="request"> Http base request</param>
        /// <param name="type">string type type parameter</param>
        public void Import(HttpRequestBase request, string type)
        {
            foreach (string fileName in request.Files)
            {
                //// get the file the user selected
                var file = request.Files[fileName];

                if (file.ContentLength <= 0)
                {
                    continue;
                }

                //// get the name of the folder in which the file will be saved on the server
                var saveFolder = ConfigurationManager.AppSettings["savefolder"];

                // creating the path for the file on the server
                var filePath = Path.Combine(
                    request.ServerVariables["APPL_PHYSICAL_PATH"] + saveFolder, 
                    Path.GetFileName(file.FileName));

                //// saving a copy of the user's posted file on the server
                file.SaveAs(filePath);

                // save the file in the database
                var id = ImportExportFileOracleContext.ImportFile(
                    DateTime.Now,
                    file.FileName,
                    filePath,
                    file.ContentType,
                    file.ContentLength,
                    Global.AuthorizedUser.Email,
                    null,
                    type);

                //// reload profile image current user (globale authorized user) 
                //// without reloading for the databse
                if (type == "IMPORT_FILE")
                {
                    Global.AuthorizedUser.ProfileImage = new FileModel()
                    {
                        FileContent = Global.GetFileContent(filePath),
                        FileName = file.FileName,
                        FileType = file.ContentType
                    };
                }
                
                //// deleting the file just imported so that the sever disk does not get full
                System.IO.File.Delete(filePath);
            }
        }

        public ActionResult GetPdf(string filePath)
        {
            var fileStream = new FileStream(filePath,
                                             FileMode.Open,
                                             FileAccess.Read
                                           );
            var fsResult = new FileStreamResult(fileStream, "application/pdf");
            return fsResult;
        }
    }
}

asp/asp/Controllers/HomeController.cs
//-----------------------------------------------------------------------
// <copyright file="HomeController.cs" company="ICT4Participation">
//     Copyright (c) ICT4Participation. All rights reserved.
// </copyright>
// <author>ICT4Participation</author>
//-----------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using asp.Data;
using Asp.Data;
using asp.Logic;
using Asp.Logic;
using Asp.Models;
using Asp.Models.Users;
using asp.Models;

namespace Asp.Controllers
{
    /// <summary>
    /// This class is the home controller
    /// the home controller contains all methods which are needed in the dashboard view
    /// </summary>
    public class HomeController : Controller
    {
        /// <summary>
        /// This repository contains all (user) methods for communicating with the database
        /// </summary>
        private readonly UserRepository userRepository = new UserRepository(new UserOracleContext());

        /// <summary>
        /// This repository contains all (question) methods for communicating with the database
        /// </summary>
        private readonly QuestionRepository questionRepository = new QuestionRepository(new QuestionOracleContext());
        
        /// <summary>
        /// This repository contains all (review) methods for communicating with the database
        /// </summary>
        private readonly ReviewRepository reviewRepository = new ReviewRepository(new ReviewOracleContext());

        /// <summary>
        /// This repository contains all (chat) methods for communicating with the database
        /// </summary>
        private readonly ChatRepository chatRepository = new ChatRepository(new ChatOracleContext());

        /// <summary>
        /// This action result will load the users dashboard
        /// unless global authorized user isn't set (user is not loged in)
        /// </summary>
        /// <returns> return view Dashboard/ redirect action sign in</returns>
        public ActionResult Dashboard()
        {
            if (Global.AuthorizedUser == null)
            {
                return this.RedirectToAction("SignIn", "Start");
            }

            try
            {
                //// depending on the usertype get
                //// the correct context will be loaded 
                switch (Global.AuthorizedUser.UserType)
                {
                    case UserType.Helpseeker:
                        Global.AllQuestions = this.questionRepository.GetQuestionsFromHelpseeker(Global.AuthorizedUser.Email);
                        if (this.TempData["ShowChat"] == null)
                        {
                            Global.AllChats = this.chatRepository.GetAllChatsFromPerson(Global.AuthorizedUser.Email);
                        }
                        break;

                    case UserType.Volunteer:
                        Global.AllQuestions = this.questionRepository.GetQuestions();
                        ((Volunteer) Global.AuthorizedUser).Reviews =
                            this.reviewRepository.GetReviewsFromVolunteer(Global.AuthorizedUser.Email);
                        if (this.TempData["ShowChat"] == null)
                        {
                            Global.AllChats = this.chatRepository.GetAllChatsFromPerson(Global.AuthorizedUser.Email);
                        }
                        break;

                    case UserType.Admin:
                        Global.AllQuestions = this.questionRepository.GetQuestions();
                        Global.AllHelpseekers = this.userRepository.GetAllHelpSeekers();
                        Global.AllVolunteers = this.userRepository.GetAllVolunteers();
                        
                        //// load all reviews for each volunteer
                        foreach (var volunteer in Global.AllVolunteers)
                        {
                            volunteer.Reviews = this.reviewRepository.GetReviewsFromVolunteer(volunteer.Email);
                        }

                        break;
                }
            }
            catch (Exception e)
            {
                //// show exception message through remodal
                this.TempData["RemodalMessage"] = new TechnicalErrorMessage(e).ErrorMessage;
                return this.RedirectToAction("SignIn", "Start");
            }


            //// depending on usertype show correct dashboard
            if (Global.AuthorizedUser.UserType == UserType.Helpseeker)
            {
                return this.View("HelpseekerDashboard", Global.AuthorizedUser);
            }
            else if (Global.AuthorizedUser.UserType == UserType.Volunteer)
            {
                return this.View("VolunteerDashboard", Global.AuthorizedUser);
            }
            else
            {
                return this.View("AdminDashboard");
            }
        }

        /// <summary>
        /// This action result will try and edit an user's profile info
        /// </summary>
        /// <param name="name"> input (new) name</param>
        /// <param name="bio">input (new) biography</param>
        /// <returns> redirect action dashboard </returns>
        [HttpPost]
        public ActionResult EditProfileInfo(string name, string bio)
        {
            try
            {
                //// Edit user on current session (global auhorized user) and in database
                var oldName = Global.AuthorizedUser.Name;
                Global.AuthorizedUser.EditProfileInfo(name, bio);
                this.userRepository.EditProfileInfo(Global.AuthorizedUser, oldName);
            }
            catch (Exception e)
            {
                //// show exception message through remodal
                this.TempData["RemodalMessage"] = new TechnicalErrorMessage(e).ErrorMessage;
            }

            return this.RedirectToAction("Dashboard");
        }

        /// <summary>
        /// This action result will try and edit an user's (about) profile info
        /// </summary>
        /// <param name="city"> input (new) city</param>
        /// <param name="dateOfBirth"> input (new) date of birth</param>
        /// <param name="publicTransport"> input (new) can use public transport state</param>
        /// <param name="hasDrivingLicense"> input (new) has driving license state</param>
        /// <param name="hasCar"> input (new) has car state</param>
        /// <returns> redirect action dashboard </returns>
        [HttpPost]
        public ActionResult EditProfileAbout(
            string city, string dateOfBirth, bool? publicTransport, bool? hasDrivingLicense, bool? hasCar)
        {
            try
            {              
                //// Edit user in the database and the (global authorized) user
                //// this way the user won't need to reload from the database
                //// (depending on what user type)
                switch (Global.AuthorizedUser.UserType)
                {   
                    case UserType.Helpseeker:
                        ((HelpSeeker)Global.AuthorizedUser).EditProfileAbout(city, Convert.ToDateTime(dateOfBirth), publicTransport, null, null);
                        this.userRepository.EditProfileAboutHelpSeeker((HelpSeeker) Global.AuthorizedUser);
                        break;

                    case UserType.Volunteer:
                        ((Volunteer)Global.AuthorizedUser).EditProfileAbout(city, Convert.ToDateTime(dateOfBirth), null, hasDrivingLicense, hasCar);
                        this.userRepository.EditProfileAboutVolunteer((Volunteer) Global.AuthorizedUser);
                        break;
                }
            }
            catch (Exception e)
            {
                //// show exception message through remodal
                this.TempData["RemodalMessage"] = new TechnicalErrorMessage(e).ErrorMessage;
            }

            return this.RedirectToAction("Dashboard");
        }

        /// <summary>
        /// This action result will try and edit the planning of a volunteer
        /// </summary>
        /// <param name="monday"> monday availability</param>
        /// <param name="tuesday"> tuesday availability</param>
        /// <param name="wednesday"> wednesday availability</param>
        /// <param name="thursday"> thursday availability</param>
        /// <param name="friday"> friday availability</param>
        /// <param name="saturday"> saturday availability</param>
        /// <param name="sunday"> sunday availability</param>
        /// <returns> redirect action dashboard </returns>
        [HttpPost]
        public ActionResult EditPlanning(
            string monday,
            string tuesday,
            string wednesday,
            string thursday,
            string friday,
            string saturday,
            string sunday)
        {
            //// put input into list
            var availabilities = new string[]
            {
                monday,
                tuesday,
                wednesday,
                thursday,
                friday,
                saturday,
                sunday
            };

            try
            {
                //// Edit (global authorized) volunteers planning
                //// this way the user won't need to reload from the database
                ((Volunteer) Global.AuthorizedUser).Availabilities = availabilities;

                //// Edit volunteer into the database
                this.userRepository.EditPlanning(availabilities);
            }
            catch (Exception e)
            {
                //// show exception message through remodal
                this.TempData["RemodalMessage"] = new TechnicalErrorMessage(e).ErrorMessage;
            }

            return this.RedirectToAction("Dashboard");
        }

        /// <summary>
        /// This action result will try and add a new question into the database

asp/asp/Views/Home/HelpseekerDashboard.cshtml
@using Asp.Models
@using Asp.Models.Users
@{
    ViewBag.Title = "Home";
    var user = Model;
    var questions = Global.AllQuestions;
}

@{ Html.RenderPartial("~/Views/Navigation/_TopNavBar.cshtml"); }

<div class="container-fluid wrap">
<div class="row">
<div class="col-md-4 col-xs-12">
    <div class="row">
        <div class="col-xs">
            <div class="box profile">
                <div>
                    <img id="profile-img" class="user-img" src="@($"data:image/png;base64,{Convert.ToBase64String(Global.AuthorizedUser.ProfileImage.FileContent)}")">
                </div>
                @using (Html.BeginForm("UploadProfileImage", "File", FormMethod.Post,
                    new {@id = "form-profile-img", @class = "display-none", @enctype = "multipart/form-data"}))
                {
                    <input type="file" id="input-profile-img" name="file"/>
                }

                <h2 class="name">@user.Name</h2>
                <p class="biography">@user.Bio</p>
                <div class="edit-img-wrapper">
                    <img class="edit-img" src="@Url.Content("~/Content/images/edit-icon-dark-gray.svg")">
                </div>

                @using (Html.BeginForm("EditProfileInfo", "Home", FormMethod.Post,
                    new {@autocomplete = "off", @class = "edit-form"}))
                {
                    <hr class="gray-separator">
                    <input type="text" class="edit-name" placeholder="Typ hier uw naam" maxlenght="20" name="name"/>

                    <textarea placeholder="Typ hier uw biografie" maxlength="400" name="bio"></textarea>
                    <input type="submit" value="Wijzig">
                }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs">
            <div class="box about">
                <h2 class="box-header">Over mij</h2>
                <ul>
                    <li>Woont in <span>@(string.IsNullOrEmpty(user.Location) ? "-" : @user.Location)</span></li>
                    <li>Geboortedatum <span>@(user.DateOfBirth?.ToString("d MMMM yyyy") ?? "-")</span></li>
                    <li>Kan met openbaar vervoer <span>@((user as HelpSeeker)?.CanUsePublicTransport == true ? "ja" : "nee")</span></li>
                </ul>

                <div class="edit-img-wrapper">
                    <img class="edit-img" src="@Url.Content("~/Content/images/edit-icon-dark-gray.svg")">
                </div>

                @using (Html.BeginForm("EditProfileAbout", "Home", FormMethod.Post,
                    new {@autocomplete = "off", @class = "edit-form"}))
                {
                    <hr class="gray-separator">
                    <ul>
                        <li>Woont in<input type="text" placeholder="Typ hier uw woonplaats" name="city"></li>
                        <li>Geboortedatum<input type="text" class="datepicker"
                                                value="@(user.DateOfBirth?.ToString("d MMMM yyyy"))"
                                                placeholder="@DateTime.Now.AddYears(-40).ToString("d MMMM yyyy")"
                                                name="dateOfbirth" style="border: none; padding: 0"/>
                        </li>
                        <li>Kan met openbaar vervoer
                            <select name="publicTransport">
                                <option value="true">ja</option>
                                <option value="false">nee</option>
                            </select>
                        </li>
                    </ul>
                    <input type="submit" value="Wijzig">
                }
            </div>
        </div>
    </div>
</div>

<div class="col-md-8 col-xs-12">
    <div id="questions" class="box">
        <h2 class="box-header">Vragen</h2>
        @{
            //// helpseeker -> show all questions, questions open and inprogress
            foreach (var question in questions)
            {
                //// depending on question status, render context
                //// inprogress -> show accepted volunteer
                ////               (to do optional: delete accepted volunteer for question)
                //// open       -> show help offered volunteers
                if (question.Status.ToUpper() == "INPROGRESS")
                {
                    <div class="question">
                        <h3 class="title">@question.Title</h3>
                        <div class="details">
                            <p class="date">@question.PostDate.ToString("d MMMM yyyy")</p>
                            <p class="state">In behandeling</p>
                            <p><b class="action">Details</b>
                            </p>
                        </div>
                        <div class="more">
                            <p>@question.Content</p>
                            <p>Locatie: <span>@question.Location</span></p>
                            <p>Vervoer: <span>@question.Transport</span></p>

                            <a href="@Url.Action("ShowUser", "Home",
                                         new {email = question.AcceptedVolunteer.Email, questionId = -1})">
                                <img class="user-img" src="@($"data:image/png;base64,{Convert.ToBase64String(question.AcceptedVolunteer.ProfileImage.FileContent)}")">
                            </a>

                            <div class="edit-img-wrapper">
                                <img class="edit-img" src="@Url.Content("~/Content/images/edit-icon-dark-gray.svg")">
                            </div>

                            <div class="edit-img-wrapper">
                                <a href="@Url.Action("ShowReview", "Home", 
                                        new { questionId = question.Id, volunteerEmail = question.AcceptedVolunteer.Email }, null)">
                                    <img class="delete-img" src="@Url.Content("~/Content/images/delete-icon.svg")">
                                </a>
                            </div>

                            @using (Html.BeginForm("EditQuestion", "Home",
                                new {id = question.Id}, FormMethod.Post,
                                new {@autocomplete = "off", @class = "edit-form"}))
                            {
                                <hr class="gray-separator">
                                <input type="text" class="edit-title" value="@question.Title" name="title">

                                <input type="text" class="edit-location" placeholder="Address"
                                       value="@question.Location" name="location">
                                <hr class="gray-separator">

                                <label>Vervoer</label>
                                <select class="edit-transport" name="transportOption">
                                    <option value="@TransportOptions.Undefined">n.v.t.</option>
                                    <option value="@TransportOptions.Walk">Te voet</option>
                                    <option value="@TransportOptions.Bike">Fiets</option>
                                    <option value="@TransportOptions.PublicTransport">Openbaar vervoer</option>
                                    <option value="@TransportOptions.Car">Auto</option>
                                    <option value="@TransportOptions.Taxi">Taxi</option>
                                    <option value="@TransportOptions.Special">Speciaal vervoer</option>
                                </select>

                                <hr class="gray-separator">

                                <textarea class="edit-content" name="content">@question.Content</textarea>
                                <input type="submit" value="Wijzig">
                            }
                        </div>
                    </div>
                }
                else
                {
                    <div class="question">
                        <h3 class="title">@question.Title</h3>
                        <div class="details">
                            <p class="date">@question.PostDate.ToString("d MMMM yyyy")</p>
                            <p class="state">Open</p>
                            <p><b class="action">Details</b>
                            </p>
                        </div>
                        <div class="more">
                            <p>@question.Content</p>
                            <p>Locatie: <span>@question.Location</span></p>
                            <p>Vervoer: <span>@question.Transport</span></p>

                            @foreach (var volunteer in question.HelpOfferedVolunteers)
                            {
                                //// show all help offered volunteer
                                <a href="@Url.Action("ShowUser", "Home",
                                             new {email = volunteer.Email, questionId = question.Id})">
                                    <img class="user-img" src="@($"data:image/png;base64,{Convert.ToBase64String(volunteer.ProfileImage.FileContent)}")">
                                </a>
                            }

                            <div class="edit-img-wrapper">
                                <img class="edit-img" src="@Url.Content("~/Content/images/edit-icon-dark-gray.svg")">
                            </div>
                            <div class="edit-img-wrapper">
                                <a href='@Url.Action("DeleteQuestion", "Home", new {id = question.Id, status = "OPEN", volunteerEmail = string.Empty})'>
                                    <img class="delete-img" src="@Url.Content("~/Content/images/delete-icon.svg")">
                                </a>
                            </div>

                            @using (Html.BeginForm("EditQuestion", "Home",
                                new {id = question.Id}, FormMethod.Post,
                                new {@autocomplete = "off", @class = "edit-form"}))
                            {
                                <hr class="gray-separator">
                                <input type="text" class="edit-title" value="@question.Title" name="title">

                                <input type="text" class="edit-location" placeholder="Address"
                                       value="@question.Location" name="location">
                                <hr class="gray-separator">

                                <label>Vervoer</label>
                                <select class="edit-transport" name="transportOption">
                                    <option value="@TransportOptions.Undefined">n.v.t.</option>
                                    <option value="@TransportOptions.Walk">Te voet</option>
                                    <option value="@TransportOptions.Bike">Fiets</option>
                                    <option value="@TransportOptions.PublicTransport">Openbaar vervoer</option>
                                    <option value="@TransportOptions.Car">Auto</option>
                                    <option value="@TransportOptions.Taxi">Taxi</option>
                                    <option value="@TransportOptions.Special">Speciaal vervoer</option>
                                </select>
                                <hr class="gray-separator">

                                <textarea class="edit-content" name="content">@question.Content</textarea>
                                <input type="submit" value="Wijzig">
                            }
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>
</div>
</div>

@{ Html.RenderPartial("~/Views/Remodal/_Chat.cshtml"); }
@{ Html.RenderPartial("~/Views/Remodal/_Review.cshtml"); }
@{ Html.RenderPartial("~/Views/Remodal/_NewQuestion.cshtml"); }